name: Android Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB      // 1
        run: ./gradlew bundleRelease

      - name: Sign AAB               // 2
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: "MIIKDwIBAzCCCcgGCSqGSIb3DQEHAaCCCbkEggm1MIIJsTCCBagGCSqGSIb3DQEHAaCCBZkEggWVMIIFkTCCBY0GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFKGMoKoIaXgxdMgFajWzBolOkszQAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQVF1gjSuHrpSF990Up+z2HgSCBNDlWDK77bLB0MzX2ergK/Xf8s8oP4yZUXV75JUWpMnOBNdsN38loVUI73qIXk5S5RWXcK9mXc8yzyv7Y78kKa7r42EF1cwaBjBg/gihSC+Jvz/0lzCo8/2iNKmV72QPmKaKgn5JAQVnmHxgoFSuM4LsAfUQDE13NV+uBl6Q/kCh0497rVPck/ODWA9MZYwDld74rAM/vI4QPY7LywchClJ8mcwAvF672THOA+J7NWApQZMEE4wIYvYoX86GHX3WK4wKsUx+Kaa0zWRbAopDe4E1Zi5Xt7S69q7OYTYPiivPWU1PW5K9tE1hnKUoCUkzJCcCPWgu3TnOyvau2UckP4S+WYQ6ryzsMtMvufFBZs6GhICsZyi80/VdTXXUWIunLe5UEpF3qr+TeSRFknxkWUXwMnhWZPpYV3fg8EpIfpOl43a57+XQlO8MhbMkKLPZ0fWn5Pat6VT9w8Mi4R8fiETsIZmHFACqwX8Xg9Fl3j0Ag2Ko7sG9eO/99rSxzs+gFXnkjZIHcIPfc5J7Rz9iyqIAhPxrZWPqfZw+PNiY+Cz1qeNpOgaPicXg2e9D7QxA8Z2zJzrqFM476Hy//s9RLKWJJ+EQq3iCh7h54HVlpND2XQq45TQR0f4sHEZz4naRmHaSQgsAdVV7zbJur6YW/WqmFJ3Q4q1sQtKSjD5OIO1BsAPd2PYyEBHvx2S69DJrTBxq4H8DZsQXD9lYVzeI0FN7GM0Lwmp/w6lCw1MGZvaSgK7Wn5QAsOHNet0+6fJqWbOymUQNKLdIOe4j7/IV6f+p0zSZXftdn4ltoCaErY097uPoaW4OQbE2jCqQ5i/pcXqEdFfmI/4lMdovxVqhdCDpx9K5kRy5vr+2FalEIliuk0ygOslGNmGRiT/+JSl5SPfczBwBqJZDMNH48Jzz2nYITjcZDLVM0CyxjeMlvZeurB34s8uulchw2JNHh2pJzmFbrzR3UqE+ba9UQ5mWkA/cS/qHCDW8KMxfLWiG6EjaknykRnwZ7Nd6CmDesR650eX4f3I63ZACayVTlW12xxWcbXVxhvgFtVPSNJ9rXL/Jon861RyvDUP5nk4Aa8w7Ur1Shi5HWV8L13w6eSNEQmmTqtXZ4f6QOodzmqZt0VkdOJvtGcfy+T5ehchuCNZuCxpI/YXOppZzNlI4x6515KLk3txcyeXIhgmiuNmPHeyjhX1akT5wqr2gNxXBdIoVA6mZPLZgDxB6yYKPwQyrjE68mcBnDNTaDFhRQEdQNYFjAJTeH5EqWH7oEnNnwDbhGsM+zlc1ldlur+OaW6rJLxFgZq94QCoVOWzWFQPrDGJ8oD4JeOXWPTyj4Rw5UNM7uNihOHe1NtxsnU4GFs6v5xAyFwW9txboF+nWWsxjt+1KmfNyojfLfj+iKavGDHmQrO4lqQrCeRTQbo6T3gexjNHx/qRTQfU6bs4RTq+BngYFnI+HX8/xtY0Gx+dIsN9zYI37N/RkkJs3pacYu5C22CMlZ9fnjNjFE8NADAQln34btFysfKH4teDJxENmwVjT4xSftuRFsMCaNHGobxKOvzT4ZaoISVrbQv0yGd1/u2fHAWwQc6A7LWHAtlJuTUvmwpmkOiM/blTD8ckK7/rNfVHuCjwW/iA8kgVOoUZ5TgFXQzE6MBUGCSqGSIb3DQEJFDEIHgYAawBpAG0wIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY2NzEyMjAyNDM4MTCCBAEGCSqGSIb3DQEHBqCCA/IwggPuAgEAMIID5wYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQtnvUDZkaN8CXWT/AtSb2cKW6xVAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEECjAY9aARnaNS6G4EGea3b6AggNwgoi9HtOWU0BNTsWrCmfPASr3Q5/Gps94E/7Dg1exqxGk/yYF7g/4rWRlAMtHpOzjHHcbol7Fo8Zp0pEfrD2QGiLW8CBzZFMtSRhTk6n/K6EgIFBMigJJ0XO7Km0pXBGzJwpWv3h4EXfjP0MdYDN11xC7hJwj2FAPpNYFalOaXWVFeJVQWoLR2ib1sH7KqoX5ABBhViA0kBIr3xffev1TGGPbZiivV1gHX31ZZcI6qjH7f2SScgGOCc7VWuRQ1jvW62qTlfy/V8127/hQxIjGYiqmS//X/ytjHWHvpEfSJvP/m0rj1pqYxggdiKPaKVtgRU/DZ7ji03JwBevH+xOrl7tFgq6l/0XVI7jc65kfK7k8ncXRJdLCkyjfJKrAadB2xUvPOqyzh/iN0opq5rZYiACLTF3mQtBf99N07JZeYJeLb815H4UWtBrEoUWLAk82H2QjWntbPtuCR6TCZe34QafBa3V8y1WlUyR75O3HIYs5PCtn3RS3BqzbxFehVsvjDMmKpsPqu/JCZ2CwB4h8Dgldp7XF+Bi1BOKkVBliSoXJzq5FYggrlltQ2uTbagyiHBoEbkCv8N6i+7YK/rrSUn/NNPWucC7H6wQyerpwGXKDwXcc9wLiaZs6vCsTgqr4bwW65mMFMG99zk3x+iShgML7/8PEyGVb8ejkqd2qdiSq3Wqt0sNpTTk8fsVCCf9+TJ6+LrjOp9aoilj+XadbTO4jtz4/T7wOmTMbt17vvh9yeycZNH/Ep0mgvSbYMuEG/wmEQuJzpRA9gqZc25YUMXkTAzzg8pgGDFdah1ASKlpf4X9kcTHT2WpuZPOC6BkdtFLFHiP+JAxv6G+MkGIOMxNzPw7auUHA99ZkeAlNGdsxE3LjXNU0c0CMqrvqZB2Lj5BuFgC8nUzMASP8Z2iW7fI04TyTjXwMfkfqbQkL4j9KS07D+bfA4yNjSAFdgH+jAi7tZY+1s36xIxG04vLTS7QcmfzWwvecsSaVUfAALgNuqxU2QuBNyqcA/XmD6GEFZqcNFRSaFnrnIoSAzmr2i7gPg3OdA4ZrQAQOhXKT5S7m4bWgzqs4lKgNGkhzOErmSrebU3DvJebmFiTfEJxDF3OLPVHIkRPxqSrd4yHM2RYKQ6eLVlIzAj2SzB3YIHdsQb8AVOPeZ5XWu8IYUYRYFjA+MCEwCQYFKw4DAhoFAAQUHfTZpqKd+9FliUlwlOW2U+B1pEAEFBBOjciZtE37JvrjNugbq9VsVLpFAgMBhqA="
          alias: "Kim"
          keyStorePassword: "Kim@8866"
          keyPassword: "Kim@8866"
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs
